## Basic Configuration

baseurl = "https://timsu.gr" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Tim Sugar"
title = "Tim Sugar"

theme = "hugo-goa"

## Hugo Built-in Features
## disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Tim Sugar"
intro = "Software Engineer"
## description = "Now @Pied Piper. Previously @Hacker Hostel, @Bachmanity and @Aviato. <br/> \"What is F times 5? It's Fleventy-five.\""
authorimage = "principle.jpg"
dateformat = "2 Jan 2006"

## Site Meta Settings
[params.meta]
description = "Contact details"
keywords = "contact,blog,developer,hugo"

## Social Accounts
[params.social]
github = "timothysugar"
## instagram = "<username>"
## linkedin = "<username>"
## twitter = "<username>"
## facebook = "<username>"
## google = "<username>"
## stackoverflow = "<username>"
email = "timothysugar@gmail.com"

## Extras
[params.extra]
copyright = "© 2018. Tim Sugar. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
